[[files]]
template = ".env.example"
output = ".env"
allow-empty = []
force-prompt-on-create = ["HANDSHAKE_PROXY", "DANE_PROXY", "PORT", "HANDSHAKE_DOMAIN", "ICANN_DOMAIN", "HSD_HOST", "HSD_PORT", "HSD_API_KEY", "PDNS_URL", "PDNS_API_KEY", "PUBLIC_IP", "PRIVATE_ICANN_KEY_PATH", "PUBLIC_ICANN_CERT_PATH", "PUBLIC_HANDSHAKE_CERT_PATH", "PRIVATE_HANDSHAKE_KEY_PATH", "HNSD_HOST", "HNSD_PORT"]
