// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/.well-known/wallets.ts";
import * as $1 from "./routes/.well-known/wallets/[symbol].ts";
import * as $2 from "./routes/[domain].tsx";
import * as $3 from "./routes/[domain]/[symbol].tsx";
import * as $4 from "./routes/about.tsx";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/api/v1/domains/[domain]/symbols/[symbol]/qrcode.ts";
import * as $7 from "./routes/api/v1/subdomains.ts";
import * as $8 from "./routes/api/v1/subdomains/[subdomain].ts";
import * as $9 from "./routes/api/v1/subdomains/[subdomain]/wallets.ts";
import * as $10 from "./routes/api/v1/subdomains/[subdomain]/wallets/[symbol].ts";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/login.tsx";
import * as $13 from "./routes/logout.ts";
import * as $14 from "./routes/signup.tsx";
import * as $15 from "./routes/subdomain.tsx";
import * as $$0 from "./islands/Address.tsx";
import * as $$1 from "./islands/CoinInput.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Key.tsx";
import * as $$4 from "./islands/NewWallet.tsx";
import * as $$5 from "./islands/QRCode.tsx";

const manifest = {
  routes: {
    "./routes/.well-known/wallets.ts": $0,
    "./routes/.well-known/wallets/[symbol].ts": $1,
    "./routes/[domain].tsx": $2,
    "./routes/[domain]/[symbol].tsx": $3,
    "./routes/about.tsx": $4,
    "./routes/api/joke.ts": $5,
    "./routes/api/v1/domains/[domain]/symbols/[symbol]/qrcode.ts": $6,
    "./routes/api/v1/subdomains.ts": $7,
    "./routes/api/v1/subdomains/[subdomain].ts": $8,
    "./routes/api/v1/subdomains/[subdomain]/wallets.ts": $9,
    "./routes/api/v1/subdomains/[subdomain]/wallets/[symbol].ts": $10,
    "./routes/index.tsx": $11,
    "./routes/login.tsx": $12,
    "./routes/logout.ts": $13,
    "./routes/signup.tsx": $14,
    "./routes/subdomain.tsx": $15,
  },
  islands: {
    "./islands/Address.tsx": $$0,
    "./islands/CoinInput.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Key.tsx": $$3,
    "./islands/NewWallet.tsx": $$4,
    "./islands/QRCode.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
